version: '3.8'

services:
  app:
    container_name: bank-app
    build: .
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"

 